- .circleci/config.yml
- src/components/greeting-modal/greeting-modal.js
> Fixed linting

- translations/ui-notes/ar.json
- translations/ui-notes/ca.json
- translations/ui-notes/da.json
- translations/ui-notes/de.json
- translations/ui-notes/en_GB.json
- translations/ui-notes/en_SE.json
- translations/ui-notes/en_US.json
- translations/ui-notes/es.json
- translations/ui-notes/es_ES.json
- translations/ui-notes/fr.json
- translations/ui-notes/fr_FR.json
- translations/ui-notes/hu.json
- translations/ui-notes/it_IT.json
- translations/ui-notes/pt_BR.json
- translations/ui-notes/pt_PT.json
- translations/ui-notes/zh_CN.json
> Update translation strings as of 20190416T182157

- src/util.js
Fixed validation for duplicate string typo
> Fixed validation

- translations/ui-notes/es_ES.json
> Update translation strings as of 20190425T181703

- package.json
Fixed version of okapiInterface module
> Fixed okapi interface version

- src/settings/note-types-settings.js
- translations/ui-notes/en.json
1) Fixed number of notes in the notes settings
2) Removed template localization strings
> UINOTES-31, UINOTES-19: Fixed number of notes and corrected localization

- CHANGELOG.md
- package.json
- yarn.lock
> Release v1.1.0

- translations/ui-notes/ar.json
- translations/ui-notes/ca.json
- translations/ui-notes/da.json
- translations/ui-notes/de.json
- translations/ui-notes/en_GB.json
- translations/ui-notes/en_SE.json
- translations/ui-notes/en_US.json
- translations/ui-notes/es.json
- translations/ui-notes/es_419.json
- translations/ui-notes/es_ES.json
- translations/ui-notes/fr.json
- translations/ui-notes/fr_FR.json
- translations/ui-notes/hu.json
- translations/ui-notes/it_IT.json
- translations/ui-notes/pt_BR.json
- translations/ui-notes/pt_PT.json
- translations/ui-notes/zh_CN.json
> Update translation strings as of 20190611T141613

- package.json
- test/bigtest/helpers/setup-application.js
- test/bigtest/network/boot.js
- yarn.lock
The purpose of this PR is to Fix security vulnerabilities in lodash and webpack-bundler-analyser
Migrated to the latest version of stripes
> UINOTES-28: Fix security vulnarabilities

- CHANGELOG.md
- package.json
- yarn.lock
> Release v1.2.0

- translations/ui-notes/de.json
- translations/ui-notes/zh_CN.json
> Update translation strings as of 20190729T163855

- CHANGELOG.md
- package.json
- yarn.lock
https://issues.folio.org/browse/UINOTES-54
Release module for the FOLIO 2019Q3.2
> Release v1.3.0

- translations/ui-notes/it_IT.json
> Update translation strings as of 20190913T225241

- translations/ui-notes/it_IT.json
> Update translation strings as of 20190919T124724

- translations/ui-notes/zh_CN.json
> Update translation strings as of 20190925T125755

- translations/ui-notes/ru.json
- translations/ui-notes/zh_TW.json
> Update translation strings as of 20191014T135140

- translations/ui-notes/ja.json
> Update translation strings as of 20191028T205642

- translations/ui-notes/he.json
> Update translation strings as of 20191113T214202

- translations/ui-notes/it_IT.json
> Update translation strings as of 20191115T154823

- translations/ui-notes/fr_FR.json
> Update translation strings as of 20191125T160504

- translations/ui-notes/fr_FR.json
> Update translation strings as of 20191127T181804

- translations/ui-notes/ru.json
> Update translation strings as of 20191202T021928

- translations/ui-notes/fr_FR.json
> Update translation strings as of 20191209T142332

- translations/ui-notes/es.json
- translations/ui-notes/es_419.json
> Update translation strings as of 20191220T210632

- translations/ui-notes/ur.json
> Update translation strings as of 20200217T172736

- translations/ui-notes/fr_FR.json
> Update translation strings as of 20200224T151433

- translations/ui-notes/ja.json
> Update translation strings as of 20200413T183215

- translations/ui-notes/ja.json
> Update translation strings as of 20200421T180634

- translations/ui-notes/zh_TW.json
> Update translation strings as of 20200424T193712

- translations/ui-notes/zh_TW.json
> Update translation strings as of 20200505T210535

- CHANGELOG.md
- package.json
> UINOTES-80 Update react-intl to v4.5

- CHANGELOG.md
- package.json
- Update `stripes` to `v4.0.0`
> UINOTES-80: Update stripes to v4

- src/settings/note-types-settings.js
- Remove deprecated `intlShape`
> UINOTES-80 Remove intlShape

- translations/ui-notes/ar.json
- translations/ui-notes/ca.json
- translations/ui-notes/da.json
- translations/ui-notes/de.json
- translations/ui-notes/en_GB.json
- translations/ui-notes/en_SE.json
- translations/ui-notes/en_US.json
- translations/ui-notes/es.json
- translations/ui-notes/es_419.json
- translations/ui-notes/es_ES.json
- translations/ui-notes/fr.json
- translations/ui-notes/fr_FR.json
- translations/ui-notes/he.json
- translations/ui-notes/hu.json
- translations/ui-notes/it_IT.json
- translations/ui-notes/ja.json
- translations/ui-notes/pt_BR.json
- translations/ui-notes/pt_PT.json
- translations/ui-notes/ru.json
- translations/ui-notes/ur.json
- translations/ui-notes/zh_CN.json
- translations/ui-notes/zh_TW.json
> Update translation strings as of 20200521T142352

- translations/ui-notes/fr_FR.json
> Update translation strings as of 20200602T151309

- CHANGELOG.md
- package.json
> Update stripes to v5

- translations/ui-notes/ber.json
- translations/ui-notes/fr_FR.json
> Update translation strings as of 20201109T135508

- translations/ui-notes/de.json
> Update translation strings as of 20201119T214636

- CHANGELOG.md
- Jenkinsfile
- package.json
Issue: [UINOTES-105](https://issues.folio.org/browse/UINOTES-105)
> UINOTES-105: Compile Translation Files into AST Format

- Jenkinsfile
- README.md
Also FOLIO-3226 Verify defaultBranch config
> FOLIO-1021 Update copyright year

- CHANGELOG.md
- package.json
Update stripes v7 and react v17
[UINOTES-110](https://issues.folio.org/browse/UINOTES-110)
> UINOTES-110: Update stripes v7 and react v17

- CHANGELOG.md
- package.json
- test/jest/__mock__/stripesConfig.mock.js
- test/jest/babel.config.js
https://issues.folio.org/browse/UINOTES-119
> Release v6.1.0

- .github/workflows/build-npm.yml
- .gitignore
- .npmrc
- Reverting previous workflow change. 
- Removing .npmrc file from repository.  See https://issues.folio.org/browse/FOLIO-3482
> Fix GA workflow

- CHANGELOG.md
- package.json
- src/settings/note-types-settings.js
- src/settings/note-types-settings.test.js
This reverts commit 57bc3ea46020daf6dd212b0a19afc9b74c27b0f9.
> Revert "UINOTES-132: Settings > Notes > General > Note types - Remove # of notes column (#191)"

- CHANGELOG.md
- package.json
Upgrade react-redux to v8
[UINOTES-140](https://issues.folio.org/browse/UINOTES-140)
> UINOTES-140 Upgrade react-redux to v8

- CHANGELOG.md
- src/settings/notes.js
- src/settings/notes.test.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-notes/en.json
Show selected setting page in the HTML page title.
[UINOTES-149](https://issues.folio.org/browse/UINOTES-149)
https://github.com/folio-org/ui-notes/assets/77053927/7f2fcee9-a079-4192-a52c-a16c51fb4faa
> UINOTES-149: Show selected setting page in the HTML page title.

- src/settings/note-types-settings.js
- src/settings/note-types-settings.test.js
- src/settings/notes.js
- src/settings/notes.test.js
Show the HTML page title `Notes settings - Note types - FOLIO` for `General` settings.
Follow-up PR.
https://github.com/folio-org/ui-notes/assets/77053927/c5f1ee76-ef75-4468-ab17-b9a51dcb309c
> UINOTES-149: Show the HTML page title 'Notes settings - Note types - FOLIO' for General settings.

- CHANGELOG.md
- package.json
> Release v9.1.0

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Verify changes in notes permissions
https://folio-org.atlassian.net/browse/UINOTES-154
Update permissions
> UINOTES-154: update notes permissions
